using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Hypocycloid.Core;
using Hypocycloid.Utils;
using UnityEngine;
using UnityEngine.Localization;

namespace Hypocycloid.Ratioscope
{
    /// <summary>
    /// Scene-level LLM runtime behind the cortex: owns model selection and lifetime, the
    /// chat history, generation streams, and manual compaction. UI components subscribe
    /// to its events and render state; they never touch ChatService directly.
    /// </summary>
    [DisallowMultipleComponent]
    [ConfigSettings("ui_cat_ai", priority: 1)]
    public sealed class CortexCore : MonoBehaviour, IConfigEnumOptionProvider
    {
        [SerializeField]
        LlmSystemSettings systemSettings;

        [SerializeField]
        LlmModelDownloader modelDownloader;

        [SerializeField]
        [Tooltip("Select a model/backend from the VRAM thresholds in System Settings.")]
        bool autoSelectSystemOption = true;

        [SerializeField]
        [ConfigSetting("ui_ai_system_prompt", priority: 18)]
        [TextArea(3, 8)]
        string systemPrompt = "You are cortex, a concise and helpful assistant.";

        [SerializeField]
        [Tooltip("Used when automatic system selection is disabled.")]
        LlmSystemOption systemOption = LlmSystemOption.Gpu1_7B_2048;

        [SerializeField]
        [Min(0)]
        [Tooltip("Maximum reply tokens. Set to 0 to use all context space left after the prompt.")]
        int maxNewTokens;

        [SerializeField]
        [ConfigSetting("ui_ai_thinking", tipKey: "ui_tip_ai_thinking", priority: 19)]
        [Tooltip(
            "Allows supported models to emit a hidden reasoning block before the answer. "
                + "Disabled by default so reasoning cannot consume the reply budget."
        )]
        bool enableThinking;

        [SerializeField]
        [ConfigSetting("ui_ai_temperature", tipKey: "ui_tip_ai_temperature", priority: 19)]
        [Range(0f, 2f)]
        float temperature = 0.7f;

        [SerializeField]
        [Tooltip("Milliseconds of model work per frame while generating.")]
        float frameBudgetMilliseconds = 8f;

        [SerializeField]
        [Tooltip("System instruction for manual compaction; localized via StringTable.")]
        LocalizedString compactionInstruction = new()
        {
            TableReference = "StringTable",
            TableEntryReference = "ui_compaction_instruction",
        };

        [SerializeField]
        [Range(32, 256)]
        [Tooltip("Maximum tokens generated by the model for compacted conversation memory.")]
        int compactedMemoryTokens = 128;

        readonly List<ChatMessage> history = new();

        ChatService service;
        ChatServiceOptions serviceOptions;
        ChatStream stream;
        ChatMessage compactedMemory;
        ChatMessage compactingUser;
        ChatMessage compactingAssistant;
        ChatGenerationOptions pendingReplyGeneration;

        bool initializationStarted;
        bool downloaderSubscribed;
#if !UNITY_STANDALONE && !UNITY_EDITOR
        bool userSelectedSystemOption;
#endif
        bool destroyed;
        string loadingModelName;
        string loadingBackend;
        long loadingModelBytes;
        double loadingStartedAt;
        double nextLoadingStatusAt;

        public bool IsModelLoading { get; private set; }
        public bool IsWaitingForModel { get; private set; }
        public string ModelLoadingStatus { get; private set; } = "Loading...";
        public bool ModelReady { get; private set; }
        public LlmSystemOption SelectedSystemOption { get; private set; }
        public ChatStream ActiveStream => stream;
        public StreamPurpose ActiveStreamPurpose { get; private set; }
        public bool IsStreaming => stream != null;
        public bool SupportsThinking => serviceOptions != null && serviceOptions.SupportsThinking;
        public bool EnableThinking => enableThinking;
        public int TransformerBlockCount => serviceOptions?.TransformerBlockCount ?? 0;
        public LlmTokenizer Tokenizer => service?.Tokenizer;
        public bool HasCompletableTurn => TryGetOldestCompleteTurn(out _, out _);

        public CortexVisualizationSettings CortexVisualization =>
            systemSettings != null ? systemSettings.CortexVisualization : null;

        /// <summary>
        /// Model choice surfaced in the config panel. Reads the effective selection; setting
        /// it pins manual selection and, once startup has happened, reloads the service with
        /// the new model while chat history is kept.
        /// </summary>
        [ConfigSetting(
            "ui_ai_select_model",
            tipKey: "ui_tip_ai_select_model",
            priority: 20,
            resync: true
        )]
        public LlmSystemOption SystemOption
        {
            get
            {
                if (initializationStarted)
                    return SelectedSystemOption;
                return ResolveSystemOption();
            }
            set
            {
                if (IsModelLoading)
                {
                    LogHelper.LogWarning(
                        "[CortexCore] Model selection is ignored while a model is loading."
                    );
                    return;
                }
                // Also reached by persisted user config, which bypasses the config panel's
                // locked-option check. Pinning Tiny in the serialized inspector field still
                // works; that path does not go through this setter.
                if (value == LlmSystemOption.Tiny)
                {
                    LogHelper.LogWarning(
                        "[CortexCore] Tiny is a random-weight test fixture whose 512-token "
                            + "vocabulary cannot serve the shipped tokenizer; selection ignored."
                    );
                    return;
                }
#if UNITY_ANDROID && !UNITY_EDITOR
                userSelectedSystemOption = true;
#endif
                autoSelectSystemOption = false;
                systemOption = value;
                if (!initializationStarted || SelectedSystemOption == value)
                    return;
                ReloadService();
            }
        }

        public event Action ModelLoadingStarted;
        public event Action<string> ModelLoadingStatusChanged;
        public event Action ModelLoadingFinished;
        public event Action<ChatRuntimeInfo> ModelBecameReady;
        public event Action<Exception> ModelLoadFailed;

        /// <summary>Raised after a stream attaches; UI hooks its own stream listeners here.</summary>
        public event Action<ChatStream, StreamPurpose> StreamStarted;

        /// <summary>Metrics plus the live parsed content and thinking text so far.</summary>
        public event Action<TokenMetrics, string, string> StreamTokenSampled;

        public event Action StreamDetached;
        public event Action<ChatResult> ReplyCompleted;

        /// <summary>Result plus whether the compacted memory message was updated.</summary>
        public event Action<ChatResult, bool> CompactionCompleted;

        /// <summary>Fired when the user cancels a running compaction; history is left unchanged.</summary>
        public event Action CompactionCancelled;

        public event Action<Exception> StreamStartFailed;

        /// <summary>Exception is null when the stream faulted without throwing.</summary>
        public event Action<Exception> StreamFaulted;

        void Update()
        {
            if (IsModelLoading && Time.realtimeSinceStartupAsDouble >= nextLoadingStatusAt)
                PublishLoadingStatus();
            if (stream != null)
                TickStream();
        }

        public void EnsureModelLoading()
        {
            if (initializationStarted)
                return;

            initializationStarted = true;
            SubscribeToModelDownloader();

            // Android reads its model and tokenizer out of the APK once before the
            // synchronous loading path below can open them.
            if (RuntimeDataPaths.IsExtractionComplete)
            {
                InitializeOrWaitForModel();
                return;
            }

            StartCoroutine(InitializeAfterExtraction());
        }

        IEnumerator InitializeAfterExtraction()
        {
            yield return RuntimeDataPaths.ExtractIfNeeded();
            modelDownloader?.RefreshIdleStatus();
            InitializeOrWaitForModel();
        }

        void InitializeOrWaitForModel()
        {
            if (systemSettings == null)
            {
                InitializeService();
                return;
            }

            SelectedSystemOption = ResolveSystemOption();
            if (systemSettings.IsOptionAvailable(SelectedSystemOption))
            {
                IsWaitingForModel = false;
                InitializeService();
                return;
            }

            IsWaitingForModel = true;
            string fileName = systemSettings.GetPreferredArtifactFileName(SelectedSystemOption);
            ModelLoadingStatus =
                $"Model download required: {fileName}. Open Settings and choose Download Models.";
            ModelLoadingStatusChanged?.Invoke(ModelLoadingStatus);
            modelDownloader?.RefreshIdleStatus();
        }

        LlmSystemOption ResolveSystemOption()
        {
            if (systemSettings == null)
                return systemOption;
#if UNITY_ANDROID && !UNITY_EDITOR
            return userSelectedSystemOption
                ? systemOption
                : systemSettings.SelectForCurrentSystem();
#else
            return autoSelectSystemOption ? systemSettings.SelectForCurrentSystem() : systemOption;
#endif
        }

        void SubscribeToModelDownloader()
        {
            if (downloaderSubscribed || modelDownloader == null)
                return;
            modelDownloader.ModelSetChanged += OnModelSetChanged;
            downloaderSubscribed = true;
        }

        void OnModelSetChanged()
        {
            if (
                !destroyed
                && IsWaitingForModel
                && systemSettings != null
                && systemSettings.IsOptionAvailable(SelectedSystemOption)
            )
                InitializeOrWaitForModel();
        }

        async void InitializeService()
        {
            try
            {
                if (systemSettings == null)
                    throw new InvalidOperationException("LLM System Settings is not assigned.");
                if (history.Count == 0 && !string.IsNullOrWhiteSpace(systemPrompt))
                    history.Add(ChatMessage.System(systemPrompt));
                SelectedSystemOption = ResolveSystemOption();
                serviceOptions = systemSettings.CreateServiceOptions(SelectedSystemOption);
            }
            catch (Exception exception)
            {
                LogHelper.LogError(exception);
                ModelLoadFailed?.Invoke(exception);
                return;
            }

            service = new ChatService(serviceOptions);
            string loadingModelPath = !string.IsNullOrEmpty(serviceOptions.DecodeModelPath)
                ? serviceOptions.DecodeModelPath
                : serviceOptions.ModelPath;
            loadingModelName =
                serviceOptions.DecodeModelAsset != null ? serviceOptions.DecodeModelAsset.name
                : serviceOptions.ModelAsset != null ? serviceOptions.ModelAsset.name
                : Path.GetFileName(loadingModelPath);
            loadingBackend = serviceOptions.Backend.ToString();
            loadingModelBytes =
                serviceOptions.DecodeModelAsset == null
                && serviceOptions.ModelAsset == null
                && File.Exists(loadingModelPath)
                    ? new FileInfo(loadingModelPath).Length
                    : 0;
            loadingStartedAt = Time.realtimeSinceStartupAsDouble;
            nextLoadingStatusAt = 0;
            IsModelLoading = true;
            PublishLoadingStatus();
            try
            {
                ModelLoadingStarted?.Invoke();
                ChatRuntimeInfo info = await service.StartAsync();
                if (destroyed)
                    return;

                ModelReady = true;
                ModelBecameReady?.Invoke(info);
            }
            catch (Exception exception)
            {
                if (!destroyed)
                {
                    LogHelper.LogError(exception);
                    // A failed start (e.g. VRAM out-of-memory after a model switch) can leave
                    // a worker and weights allocated; release them instead of leaking.
                    service?.Dispose();
                    service = null;
                    ModelLoadFailed?.Invoke(exception);
                }
            }
            finally
            {
                IsModelLoading = false;
                ModelLoadingFinished?.Invoke();
            }
        }

        /// <summary>Stops any active stream, disposes the service, and loads SystemOption.</summary>
        void ReloadService()
        {
            ModelReady = false;
            if (stream != null)
            {
                stream.Cancel();
                FinishFaultedStream(null);
            }
            service?.Dispose();
            service = null;
            serviceOptions = null;
            // The dropped model holds multi-GiB managed weight arrays; collect now so the
            // next load does not stack on top of them.
            GC.Collect();
            InitializeOrWaitForModel();
        }

        /// <summary>
        /// Locks the tiny test fixture and marks profiles whose artifact still needs downloading.
        /// </summary>
        public bool TryGetEnumOption(
            string i18nKey,
            object enumValue,
            out string label,
            out bool enabled
        )
        {
            label = null;
            enabled = true;
            if (i18nKey != "ui_ai_select_model" || enumValue is not LlmSystemOption option)
                return false;
            if (option == LlmSystemOption.Tiny)
            {
                label = StringHelper.NicifyVariableName(option.ToString()) + " (test only)";
                enabled = false;
                return true;
            }
            if (systemSettings == null || systemSettings.IsOptionAvailable(option))
                return false;
            label = StringHelper.NicifyVariableName(option.ToString()) + " (download required)";
            enabled = true;
            return true;
        }

        void PublishLoadingStatus()
        {
            double elapsed = Math.Max(0, Time.realtimeSinceStartupAsDouble - loadingStartedAt);
            string size =
                loadingModelBytes > 0
                    ? $" | {loadingModelBytes / (1024d * 1024d * 1024d):0.0} GiB"
                    : "";
            string backendHint = loadingBackend == "CPU" ? " | GPU is not used" : "";
            ModelLoadingStatus =
                $"Loading {loadingModelName} | {loadingBackend}{size} | {elapsed:0}s"
                + $"\nReading and preparing model{backendHint}";
            ModelLoadingStatusChanged?.Invoke(ModelLoadingStatus);
            nextLoadingStatusAt = Time.realtimeSinceStartupAsDouble + 1;
        }

        void TickStream()
        {
            try
            {
                stream.Tick(frameBudgetMilliseconds);
            }
            catch (Exception exception)
            {
                LogHelper.LogError(exception);
                FinishFaultedStream(exception);
                return;
            }

            if (stream == null)
                return;
            if (
                stream.State != ChatStreamState.Thinking
                && stream.State != ChatStreamState.Completed
            )
                FinishFaultedStream(null);
        }

        /// <summary>Appends the user message to history and starts the reply stream.</summary>
        public void BeginReply(string userText)
        {
            if (!ModelReady || stream != null)
                return;

            history.Add(ChatMessage.User(userText));
            pendingReplyGeneration = CreateReplyGenerationOptions(enableThinking);
            try
            {
                AttachStream(
                    service.BeginChat(history, pendingReplyGeneration),
                    StreamPurpose.Reply
                );
            }
            catch (Exception exception)
            {
                HandleStreamStartFailure(exception);
            }
        }

        /// <summary>Starts one manual compaction pass; false when no complete turn exists.</summary>
        public bool BeginCompaction()
        {
            if (!ModelReady || stream != null)
                return false;
            if (!TryGetOldestCompleteTurn(out ChatMessage user, out ChatMessage assistant))
                return false;

            compactingUser = user;
            compactingAssistant = assistant;
            ChatGenerationOptions generation = new()
            {
                MaxNewTokens = compactedMemoryTokens,
                Temperature = 0f,
                EnableThinking = false,
            };
            try
            {
                AttachStream(
                    service.BeginChat(BuildCompactionMessages(user, assistant), generation),
                    StreamPurpose.Compaction
                );
            }
            catch (Exception exception)
            {
                HandleStreamStartFailure(exception);
            }
            return true;
        }

        /// <summary>
        /// Stops the active stream at the user's request. A cancelled reply keeps the tokens
        /// generated so far as the assistant turn; a cancelled compaction is discarded and
        /// leaves history untouched. No-op when nothing is streaming.
        /// </summary>
        public void CancelActiveStream()
        {
            if (stream == null)
                return;

            StreamPurpose purpose = ActiveStreamPurpose;
            ChatResult partial = stream.CancelWithPartialResult();

            if (purpose == StreamPurpose.Reply)
            {
                history.Add(ChatMessage.Assistant(partial.Content));
                pendingReplyGeneration = null;
                DetachStream();
                ReplyCompleted?.Invoke(partial);
            }
            else
            {
                compactingUser = null;
                compactingAssistant = null;
                DetachStream();
                CompactionCancelled?.Invoke();
            }
        }

        /// <summary>
        /// Starts a new conversation: drops every message after the startup system prompt and
        /// discards compacted memory. Ignored while a stream is running.
        /// </summary>
        public void ClearHistory()
        {
            if (stream != null)
                return;

            int conversationStart = history.Count > 0 && history[0].Role == "system" ? 1 : 0;
            if (history.Count > conversationStart)
                history.RemoveRange(conversationStart, history.Count - conversationStart);
            compactedMemory = null;
        }

        /// <summary>Replaces completed user/assistant turns while retaining the system prompt.</summary>
        public bool ReplaceConversation(IReadOnlyList<ChatMessage> messages)
        {
            if (stream != null || messages == null)
                return false;

            for (int i = 0; i < messages.Count; i++)
            {
                ChatMessage message = messages[i];
                if (message == null || (message.Role != "user" && message.Role != "assistant"))
                    throw new ArgumentException(
                        "Conversation can only contain user and assistant messages.",
                        nameof(messages)
                    );
            }

            history.Clear();
            if (!string.IsNullOrWhiteSpace(systemPrompt))
                history.Add(ChatMessage.System(systemPrompt));
            for (int i = 0; i < messages.Count; i++)
                history.Add(new ChatMessage(messages[i].Role, messages[i].Content));
            compactedMemory = null;
            compactingUser = null;
            compactingAssistant = null;
            pendingReplyGeneration = null;
            return true;
        }

        /// <summary>Prompt snapshot for the pending or default reply generation.</summary>
        public ChatContextSnapshot InspectContext()
        {
            ChatGenerationOptions generation =
                pendingReplyGeneration ?? CreateReplyGenerationOptions(enableThinking);
            return service.InspectContext(history, generation);
        }

        ChatGenerationOptions CreateReplyGenerationOptions(bool thinking)
        {
            // ChatStream independently clamps this to the prompt's remaining fixed window.
            // Using the full window removes the arbitrary 512-token cutoff while preserving
            // a hard bound if the model never emits its stop token.
            int tokenLimit =
                maxNewTokens > 0
                    ? maxNewTokens
                    : Math.Max(1, service?.RuntimeInfo?.ContextLength ?? 1);
            return new ChatGenerationOptions
            {
                MaxNewTokens = tokenLimit,
                Temperature = temperature,
                EnableThinking = thinking,
            };
        }

        public bool IsMemoryMessage(ChatMessage message) =>
            ReferenceEquals(message, compactedMemory);

        void AttachStream(ChatStream next, StreamPurpose purpose)
        {
            stream = next;
            ActiveStreamPurpose = purpose;
            stream.TokenSampled += OnTokenSampled;
            stream.Completed += OnCompleted;
            StreamStarted?.Invoke(stream, purpose);
        }

        void DetachStream()
        {
            if (stream != null)
            {
                stream.TokenSampled -= OnTokenSampled;
                stream.Completed -= OnCompleted;
            }
            stream = null;
            StreamDetached?.Invoke();
        }

        void OnTokenSampled(TokenMetrics metrics)
        {
            // The parser needs generation control markers such as <think> and </think> to
            // keep reasoning out of the visible answer while it streams. Preserve added
            // tokens explicitly even if a future tokenizer marks those delimiters special.
            string raw = service.Tokenizer.Decode(
                stream.GeneratedIds,
                skipSpecialTokens: false
            );
            ChatService.ParseStreamingResponse(
                raw,
                out string live,
                out string liveThinking,
                out _
            );
            StreamTokenSampled?.Invoke(metrics, live, liveThinking);
        }

        void OnCompleted(ChatResult result)
        {
            if (ActiveStreamPurpose == StreamPurpose.Compaction)
                OnCompactionCompleted(result);
            else if (TryRetryReplyWithoutThinking(result))
                return;
            else
                OnReplyCompleted(result);
        }

        bool TryRetryReplyWithoutThinking(ChatResult result)
        {
            if (
                pendingReplyGeneration == null
                || !pendingReplyGeneration.EnableThinking
                || (result.IsComplete && result.Content.Length > 0)
            )
                return false;

            LogHelper.LogWarning(
                $"[CortexCore] Thinking reply produced no complete visible answer "
                    + $"({result.FinishReason}; prompt={result.PromptTokens}, "
                    + $"generated={result.GeneratedTokens}, thinkingChars={result.Thinking.Length}). "
                    + "Retrying once with thinking disabled."
            );

            DetachStream();
            pendingReplyGeneration = CreateReplyGenerationOptions(false);
            try
            {
                AttachStream(
                    service.BeginChat(history, pendingReplyGeneration),
                    StreamPurpose.Reply
                );
            }
            catch (Exception exception)
            {
                HandleStreamStartFailure(exception);
            }
            return true;
        }

        void OnReplyCompleted(ChatResult result)
        {
            if (!result.IsComplete && result.FinishReason != ChatFinishReason.Cancelled)
            {
                LogHelper.LogWarning(
                    $"[CortexCore] Reply ended without a model stop token: "
                        + $"reason={result.FinishReason}, prompt={result.PromptTokens}, "
                        + $"generated={result.GeneratedTokens}, "
                        + $"window={service.RuntimeInfo.ContextLength}."
                );
            }
            history.Add(ChatMessage.Assistant(result.Content));
            pendingReplyGeneration = null;
            DetachStream();
            ReplyCompleted?.Invoke(result);
        }

        void OnCompactionCompleted(ChatResult result)
        {
            string memory = result.Content.Trim();
            DetachStream();

            bool memoryUpdated = memory.Length > 0;
            if (memoryUpdated)
            {
                history.Remove(compactingUser);
                history.Remove(compactingAssistant);
                if (compactedMemory != null)
                    history.Remove(compactedMemory);
                compactedMemory = ChatMessage.System("Conversation memory: " + memory);
                history.Insert(Math.Min(1, history.Count), compactedMemory);
            }

            compactingUser = null;
            compactingAssistant = null;
            CompactionCompleted?.Invoke(result, memoryUpdated);
        }

        void FinishFaultedStream(Exception exception)
        {
            DetachStream();
            pendingReplyGeneration = null;
            StreamFaulted?.Invoke(exception);
        }

        void HandleStreamStartFailure(Exception exception)
        {
            LogHelper.LogError(exception);
            pendingReplyGeneration = null;
            StreamStartFailed?.Invoke(exception);
        }

        bool TryGetOldestCompleteTurn(out ChatMessage user, out ChatMessage assistant)
        {
            for (int i = 0; i + 1 < history.Count; i++)
            {
                if (history[i].Role == "user" && history[i + 1].Role == "assistant")
                {
                    user = history[i];
                    assistant = history[i + 1];
                    return true;
                }
            }

            user = null;
            assistant = null;
            return false;
        }

        // Localized compaction instruction, resolved synchronously at use. Falls back to the
        // English text if the string table cannot be resolved (e.g. before localization inits).
        string ResolveCompactionInstruction()
        {
            try
            {
                string localized = compactionInstruction.GetLocalizedString();
                if (!string.IsNullOrWhiteSpace(localized))
                    return localized;
            }
            catch (Exception exception)
            {
                LogHelper.LogWarning(
                    $"[CortexCore] Compaction instruction localization failed: {exception.Message}"
                );
            }
            return "Missing Locale.";
        }

        IReadOnlyList<ChatMessage> BuildCompactionMessages(ChatMessage user, ChatMessage assistant)
        {
            StringBuilder source = new();
            if (compactedMemory != null)
                source.Append("Existing memory:\n").Append(compactedMemory.Content).Append('\n');
            source
                .Append("User:\n")
                .Append(user.Content)
                .Append("\nAssistant:\n")
                .Append(assistant.Content);

            List<int> sourceIds = service.Tokenizer.Encode(source.ToString());
            int maxPromptTokens = service.RuntimeInfo.ContextLength - compactedMemoryTokens;
            int sourceTokenCount = sourceIds.Count;
            while (true)
            {
                string content = service.Tokenizer.Decode(
                    sourceIds.GetRange(0, sourceTokenCount),
                    skipSpecialTokens: false
                );
                ChatMessage[] messages =
                {
                    ChatMessage.System(ResolveCompactionInstruction()),
                    ChatMessage.User(content),
                };
                int promptTokens = service
                    .Tokenizer.EncodeWithSpecialTokens(
                        ChatTemplate.BuildPromptText(messages, serviceOptions.SupportsThinking)
                    )
                    .Count;
                if (promptTokens <= maxPromptTokens)
                    return messages;
                if (sourceTokenCount == 0)
                    throw new InvalidOperationException(
                        "The compaction instruction does not fit the model context."
                    );

                sourceTokenCount = Math.Max(
                    0,
                    sourceTokenCount - Math.Max(1, promptTokens - maxPromptTokens)
                );
            }
        }

        void OnDestroy()
        {
            destroyed = true;
            if (downloaderSubscribed && modelDownloader != null)
                modelDownloader.ModelSetChanged -= OnModelSetChanged;
            stream?.Cancel();
            service?.Dispose();
        }
    }
}
