using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Hypocycloid.Ratioscope;
using NUnit.Framework;
using SFB;
using TMPro;
using Unity.InferenceEngine;
using UnityEditor;
using UnityEngine;
using UnityEngine.TestTools;
using Object = UnityEngine.Object;

namespace Hypocycloid.Editor
{
    /// <summary>
    /// Validates the Sentis LLM chat runtime (current checkpoint: Qwen3-4B-Instruct-2507).
    /// Tokenizer and template tests replay fixtures generated by the Hugging Face tokenizer
    /// (export_llm_tokenizer.py); model tests exercise the fixed-context decode loop
    /// end-to-end.
    /// </summary>
    public sealed class LlmChatTests
    {
        static string TokenizerPath =>
            Path.Combine(Application.streamingAssetsPath, "Llm", "llm_tokenizer.bin");

        static LlmSystemSettings SystemSettings =>
            AssetDatabase.LoadAssetAtPath<LlmSystemSettings>(
                "Assets/Bundles/Settings/LlmSystemSettings.asset"
            );

        static string FixturesPath =>
            Path.Combine(
                Application.dataPath,
                "Editor",
                "Tests",
                "Fixtures",
                "llm_tokenizer_fixtures.json"
            );

        static string SentisModelPath(string fileName) =>
            Path.Combine(Application.streamingAssetsPath, "Sentis", fileName);

        static LlmTokenizer CachedTokenizer { get; set; }
        static TokenizerFixtures CachedFixtures { get; set; }

        [Serializable]
        sealed class TokenizerFixtures
        {
            public EncodeCase[] encodeCases = Array.Empty<EncodeCase>();
            public ChatMessageFixture[] chatMessages = Array.Empty<ChatMessageFixture>();
            public int[] chatIds = Array.Empty<int>();
            public string chatText = "";
        }

        [Serializable]
        sealed class EncodeCase
        {
            public string text = "";
            public int[] ids = Array.Empty<int>();
        }

        [Serializable]
        sealed class ChatMessageFixture
        {
            public string role = "";
            public string content = "";
        }

        static LlmTokenizer Tokenizer => CachedTokenizer ??= new LlmTokenizer(TokenizerPath);

        static TokenizerFixtures Fixtures =>
            CachedFixtures ??= JsonUtility.FromJson<TokenizerFixtures>(
                File.ReadAllText(FixturesPath)
            );

        [Test]
        public void MessageRejectsUnknownRole()
        {
            Assert.Throws<ArgumentException>(() => new ChatMessage("tool", "result"));
        }

        [Test]
        public void DialogueFileRoundTripsRolesAndMultilineContent()
        {
            ChatMessage[] source =
            {
                ChatMessage.User("First line\nSecond line"),
                ChatMessage.Assistant("Answer with a \"quote\"."),
            };

            string text = ChatDialogueFile.Serialize(source);
            Assert.That(
                ChatDialogueFile.TryDeserialize(text, out List<ChatMessage> loaded, out string error),
                Is.True,
                error
            );
            Assert.That(
                loaded.Select(message => message.Role),
                Is.EqualTo(source.Select(message => message.Role))
            );
            Assert.That(
                loaded.Select(message => message.Content),
                Is.EqualTo(source.Select(message => message.Content))
            );
        }

        [Test]
        public void DialogueFileRejectsUnsupportedVersion()
        {
            bool valid = ChatDialogueFile.TryDeserialize(
                "{\"version\":2,\"messages\":[]}",
                out _,
                out string error
            );

            Assert.That(valid, Is.False);
            Assert.That(error, Does.Contain("version"));
        }

        [TestCase("Ratioscope-dialogue-20260721-214729.txt", "txt")]
        [TestCase("Ratioscope-dialogue-20260721-214729.TXT", ".txt")]
        [TestCase("Ratioscope-dialogue-20260721-214729", "txt")]
        public void SaveDialogAddsTextExtensionExactlyOnce(string defaultName, string extension)
        {
            MethodInfo buildName = typeof(StandaloneFileBrowserEditor).GetMethod(
                "BuildSaveFileName",
                BindingFlags.Static | BindingFlags.NonPublic
            );
            Assert.That(buildName, Is.Not.Null);
            string result = (string)buildName.Invoke(null, new object[] { defaultName, extension });

            Assert.That(result, Is.EqualTo("Ratioscope-dialogue-20260721-214729.txt").IgnoreCase);
            Assert.That(result, Does.Not.EndWith(".txt.txt").IgnoreCase);
        }

        [Test]
        public void ImportedConversationReplacesHistoryAndKeepsSystemPrompt()
        {
            GameObject host = new(nameof(ImportedConversationReplacesHistoryAndKeepsSystemPrompt));
            try
            {
                CortexCore cortex = host.AddComponent<CortexCore>();
                typeof(CortexCore)
                    .GetField("systemPrompt", BindingFlags.Instance | BindingFlags.NonPublic)
                    .SetValue(cortex, "System prompt");
                ChatMessage[] imported =
                {
                    ChatMessage.User("Previous question"),
                    ChatMessage.Assistant("Previous answer"),
                };

                Assert.That(cortex.ReplaceConversation(imported), Is.True);
                var history = (List<ChatMessage>)
                    typeof(CortexCore)
                        .GetField("history", BindingFlags.Instance | BindingFlags.NonPublic)
                        .GetValue(cortex);
                Assert.That(
                    history.Select(message => message.Role),
                    Is.EqualTo(new[] { "system", "user", "assistant" })
                );
                Assert.That(
                    history.Select(message => message.Content),
                    Is.EqualTo(new[] { "System prompt", "Previous question", "Previous answer" })
                );
            }
            finally
            {
                Object.DestroyImmediate(host);
            }
        }

        [Test]
        public void TinyModelCannotBeSelectedAtRuntime()
        {
            GameObject host = new(nameof(TinyModelCannotBeSelectedAtRuntime));
            try
            {
                CortexCore cortex = host.AddComponent<CortexCore>();
                cortex.SystemOption = LlmSystemOption.Cpu1_7B_2048;
                Assert.That(cortex.SystemOption, Is.EqualTo(LlmSystemOption.Cpu1_7B_2048));

                // Persisted user config assigns straight through this setter, so the config
                // panel's locked-option check is not the only thing that has to refuse Tiny.
                LogAssert.ignoreFailingMessages = true;
                cortex.SystemOption = LlmSystemOption.Tiny;
                Assert.That(cortex.SystemOption, Is.EqualTo(LlmSystemOption.Cpu1_7B_2048));

                bool locked = cortex.TryGetEnumOption(
                    "ui_ai_select_model",
                    LlmSystemOption.Tiny,
                    out string label,
                    out bool enabled
                );
                Assert.That(locked, Is.True);
                Assert.That(enabled, Is.False);
                Assert.That(label, Does.Contain("test only"));
            }
            finally
            {
                LogAssert.ignoreFailingMessages = false;
                Object.DestroyImmediate(host);
            }
        }

        [TestCase(LlmSystemOption.Tiny, BackendType.CPU, "Llm_Tiny_Decode_128.sentis", false, 4, 512)]
        [TestCase(
            LlmSystemOption.Gpu1_7B_2048,
            BackendType.GPUCompute,
            "Llm_Decode_2048.sentis",
            true,
            28,
            151936
        )]
        [TestCase(
            LlmSystemOption.Cpu1_7B_2048,
            BackendType.CPU,
            "Llm_Decode_2048.sentis",
            true,
            28,
            151936
        )]
        [TestCase(
            LlmSystemOption.Gpu4B_4096,
            BackendType.GPUCompute,
            "Llm_Decode_4096.sentis",
            false,
            36,
            151936
        )]
        [TestCase(
            LlmSystemOption.Cpu4B_4096,
            BackendType.CPU,
            "Llm_Decode_4096.sentis",
            false,
            36,
            151936
        )]
        public void SystemOptionMapsToExpectedRuntime(
            LlmSystemOption option,
            BackendType backend,
            string artifact,
            bool supportsThinking,
            int transformerBlockCount,
            int vocabularySize
        )
        {
            Assert.That(SystemSettings, Is.Not.Null);
            ChatServiceOptions options = SystemSettings.CreateServiceOptions(option);

            Assert.That(options.Backend, Is.EqualTo(backend));
            Assert.That(Path.GetFileName(options.DecodeModelPath), Is.EqualTo(artifact));
            Assert.That(options.SupportsThinking, Is.EqualTo(supportsThinking));
            Assert.That(options.TransformerBlockCount, Is.EqualTo(transformerBlockCount));
            Assert.That(options.VocabularySize, Is.EqualTo(vocabularySize));
        }

        [Test]
        public void SystemSettingsSelectExpectedVramTier()
        {
            LlmSystemSettings settings = SystemSettings;
            Assert.That(settings, Is.Not.Null);
            Assert.That(
                settings.SelectForUsableVram(3.79f),
                Is.EqualTo(LlmSystemOption.Cpu1_7B_2048)
            );
            Assert.That(
                settings.SelectForUsableVram(3.8f),
                Is.EqualTo(LlmSystemOption.Gpu1_7B_2048)
            );
            Assert.That(
                settings.SelectForUsableVram(7.79f),
                Is.EqualTo(LlmSystemOption.Gpu1_7B_2048)
            );
            Assert.That(settings.SelectForUsableVram(7.8f), Is.EqualTo(LlmSystemOption.Gpu4B_4096));
            Assert.That(
                settings.SelectForUsableVram(12f, hasGpu: false),
                Is.EqualTo(LlmSystemOption.Cpu1_7B_2048)
            );
        }

        [Test]
        public void ModelManifestProvidesProductionArtifacts()
        {
            LlmModelManifest manifest = SystemSettings.LoadManifest();

            Assert.That(manifest.Find("Llm_Decode_2048.sentis"), Is.Not.Null);
            Assert.That(manifest.Find("Llm_Decode_4096.sentis"), Is.Not.Null);
        }

        [Test]
        public void CpuFallbackDownloadsOnlyItsDecodeArtifact()
        {
            LlmModelManifest manifest = SystemSettings.LoadManifest();
            string artifact = SystemSettings.GetPreferredArtifactFileName(
                LlmSystemOption.Cpu1_7B_2048
            );

            Assert.That(artifact, Is.EqualTo("Llm_Decode_2048.sentis"));
            Assert.That(manifest.Find(artifact), Is.Not.Null);
        }

        [Test]
        public void MissingProductionProfileRemainsSelectableForDownload()
        {
            var owner = new GameObject("CortexCore download selection test");
            try
            {
                var core = owner.AddComponent<CortexCore>();
                typeof(CortexCore)
                    .GetField("systemSettings", BindingFlags.Instance | BindingFlags.NonPublic)
                    ?.SetValue(core, SystemSettings);

                core.SystemOption = LlmSystemOption.Gpu4B_4096;
                bool customized = core.TryGetEnumOption(
                    "ui_ai_select_model",
                    LlmSystemOption.Gpu4B_4096,
                    out string label,
                    out bool enabled
                );

                Assert.That(core.SystemOption, Is.EqualTo(LlmSystemOption.Gpu4B_4096));
                Assert.That(enabled, Is.True);
                if (!SystemSettings.IsOptionAvailable(LlmSystemOption.Gpu4B_4096))
                {
                    Assert.That(customized, Is.True);
                    StringAssert.Contains("download required", label);
                }
            }
            finally
            {
                Object.DestroyImmediate(owner);
            }
        }

        [Test]
        public void SpecialTokenIdsMatchCheckpointConfig()
        {
            Assert.That(Tokenizer.PadTokenId, Is.EqualTo(151643));
            Assert.That(Tokenizer.EosTokenId, Is.EqualTo(151643));
            Assert.That(Tokenizer.EndOfTurnTokenId, Is.EqualTo(151645));
            Assert.That(Tokenizer.VocabularySize, Is.EqualTo(151643));
        }

        [Test]
        public void EncodeMatchesHuggingFaceFixtures()
        {
            foreach (EncodeCase fixture in Fixtures.encodeCases)
            {
                List<int> ids = Tokenizer.Encode(fixture.text);
                Assert.That(ids, Is.EqualTo(fixture.ids), "Mismatch for: " + fixture.text);
            }
        }

        [Test]
        public void DecodeRoundTripsFixtureTexts()
        {
            foreach (EncodeCase fixture in Fixtures.encodeCases)
            {
                string text = Tokenizer.Decode(fixture.ids);
                Assert.That(text, Is.EqualTo(fixture.text));
            }
        }

        [Test]
        public void ChatTemplateTextMatchesHuggingFace()
        {
            List<ChatMessage> messages = FixtureMessages();
            string prompt = ChatTemplate.BuildPromptText(messages);
            Assert.That(prompt, Is.EqualTo(Fixtures.chatText));
        }

        [Test]
        public void ChatTemplateIdsMatchHuggingFace()
        {
            List<ChatMessage> messages = FixtureMessages();
            string prompt = ChatTemplate.BuildPromptText(messages);
            List<int> ids = Tokenizer.EncodeWithSpecialTokens(prompt);
            Assert.That(ids, Is.EqualTo(Fixtures.chatIds));
        }

        [Test]
        public void ChatTemplateCanDisableThinkingForUtilityGeneration()
        {
            string prompt = ChatTemplate.BuildPromptText(FixtureMessages(), true);

            Assert.That(prompt, Does.EndWith("<think>\n\n</think>\n\n"));
        }

        [Test]
        public void StreamingResponseSeparatesThinkingFromVisibleContent()
        {
            AssertStreamingResponse("<thi", "", "", true);
            AssertStreamingResponse("<think>\nconsidering", "", "considering", true);
            AssertStreamingResponse(
                "<think>\nconsidering\n</think>\n\nAnswer",
                "Answer",
                "considering",
                true
            );
            AssertStreamingResponse("Direct answer", "Direct answer", "", false);
        }

        [Test]
        public void TokenMetricsExtractFullSoftmaxEntropyAndTopCandidates()
        {
            TokenMetrics metrics = TokenMetrics.FromLogits(new[] { 0f, 1f, 2f }, 2);

            Assert.That(metrics.Entropy, Is.EqualTo(0.8323956f).Within(0.000001f));
            Assert.That(metrics.TopCandidates.Count, Is.EqualTo(2));
            Assert.That(metrics.TopCandidates[0].Id, Is.EqualTo(2));
            Assert.That(
                metrics.TopCandidates[0].Probability,
                Is.EqualTo(0.665241f).Within(0.000001f)
            );
            Assert.That(metrics.TopCandidates[1].Id, Is.EqualTo(1));
            Assert.That(
                metrics.TopCandidates[1].Probability,
                Is.EqualTo(0.2447285f).Within(0.000001f)
            );
        }

        [Test]
        public void CortexHeatGridMapsSignalsAndDecaysMonotonically()
        {
            CortexHeatGrid grid = new(16, 4, 2, 1f, 1.4f, 0.25f, 0.3f);
            grid.OnForward();

            CortexCellInfo structureCell = Enumerable
                .Range(0, grid.Width * grid.Height)
                .Select(index => grid.GetCell(index % grid.Width, index / grid.Width))
                .First(cell => cell.TransformerBlock == 2);
            Assert.That(structureCell.Branch, Is.EqualTo("attention"));
            Assert.That(structureCell.Stage, Is.Not.Empty);
            Assert.That(structureCell.Heat, Is.EqualTo(1f));

            TokenMetrics metrics = TokenMetrics.FromLogits(new[] { 0f, 1f, 2f }, 2);
            grid.OnToken(metrics);
            int tokenIndex = grid.TokenCellIndex(2);
            CortexCellInfo tokenCell = grid.GetCell(
                tokenIndex % grid.Width,
                tokenIndex / grid.Width
            );
            float heatBeforeDecay = tokenCell.Heat;

            Assert.That(tokenCell.Region, Is.EqualTo("token surface"));
            Assert.That(tokenCell.TokenId, Is.EqualTo(2));
            Assert.That(tokenCell.Probability, Is.EqualTo(0.665241f).Within(0.000001f));
            Assert.That(grid.TokenCellIndex(2), Is.EqualTo(tokenIndex));

            grid.Decay(0.5f);
            Assert.That(grid.Heat[tokenIndex], Is.GreaterThan(0f).And.LessThan(heatBeforeDecay));
        }

        [TestCase(28)]
        [TestCase(36)]
        public void CortexHeatGridMapsEveryTransformerBlock(int blockCount)
        {
            CortexHeatGrid grid = new(32, blockCount, 4, 1f, 1.4f, 0.25f, 0.3f);
            grid.OnForward();

            Assert.That(grid.TransformerBlockCount, Is.EqualTo(blockCount));
            Assert.That(grid.Width, Is.EqualTo(blockCount * CortexHeatGrid.ColumnsPerBlock));
            Assert.That(grid.Height, Is.EqualTo(grid.StructureRows + grid.TokenRows));
            for (int block = 0; block < blockCount; block++)
            {
                int x = block * CortexHeatGrid.ColumnsPerBlock;
                CortexCellInfo attention = grid.GetCell(x, grid.TokenRows);
                CortexCellInfo mlp = grid.GetCell(x + 1, grid.TokenRows);
                Assert.That(attention.TransformerBlock, Is.EqualTo(block));
                Assert.That(attention.Branch, Is.EqualTo("attention"));
                Assert.That(attention.Heat, Is.GreaterThan(0f));
                Assert.That(mlp.TransformerBlock, Is.EqualTo(block));
                Assert.That(mlp.Branch, Is.EqualTo("MLP"));
                Assert.That(mlp.Heat, Is.GreaterThan(0f));
            }
        }

        [TestCase(28)]
        [TestCase(36)]
        public void CortexMatrixVolumeBuildsOneQuadPerCell(int blockCount)
        {
            const int structureRows = 64;
            const int tokenRows = 8;
            int columns = blockCount * CortexHeatGrid.ColumnsPerBlock;
            MethodInfo build = typeof(CortexMatrixVolume).GetMethod(
                "BuildCellMesh",
                BindingFlags.Static | BindingFlags.NonPublic
            );
            Assert.That(build, Is.Not.Null);

            Mesh mesh = (Mesh)
                build.Invoke(
                    null,
                    new object[] { columns, structureRows, tokenRows, 0.72f, 1.08f, 0.3f }
                );
            try
            {
                int cellCount = columns * (structureRows + tokenRows);
                Assert.That(mesh.vertexCount, Is.EqualTo(cellCount * 4));
                Assert.That(mesh.GetIndexCount(0), Is.EqualTo((uint)(cellCount * 6)));
            }
            finally
            {
                Object.DestroyImmediate(mesh);
            }
        }

        [Test]
        public void CortexMatrixFoldedMappingClosesSeamAndLowersTokenDisk()
        {
            MethodInfo calculate = typeof(CortexMatrixVolume).GetMethod(
                "CalculateFoldedPosition",
                BindingFlags.Static | BindingFlags.NonPublic
            );
            Assert.That(calculate, Is.Not.Null);

            object[] Shape(float u, float vertical, bool token) =>
                new object[] { u, vertical, token, 0.72f, 1.08f, 0.3f };
            Vector3 seamStart = (Vector3)calculate.Invoke(null, Shape(0f, 0.5f, false));
            Vector3 seamEnd = (Vector3)calculate.Invoke(null, Shape(1f, 0.5f, false));
            Vector3 columnBottom = (Vector3)calculate.Invoke(null, Shape(0.25f, 0f, false));
            Vector3 diskOuter = (Vector3)calculate.Invoke(null, Shape(0.25f, 0f, true));

            Assert.That(Vector3.Distance(seamStart, seamEnd), Is.LessThan(0.0001f));
            Assert.That(diskOuter.y, Is.LessThan(columnBottom.y));
            Assert.That(
                new Vector2(diskOuter.x, diskOuter.z).magnitude,
                Is.EqualTo(1.08f).Within(0.0001f)
            );
        }

        [Test]
        public void CortexVisualizationRejectsHaloInsideColumn()
        {
            CortexVisualizationSettings settings = new();
            BindingFlags fields = BindingFlags.Instance | BindingFlags.NonPublic;
            void Set(string name, object value) =>
                typeof(CortexVisualizationSettings)
                    .GetField(name, fields)
                    .SetValue(settings, value);

            Set("stageRows", 64);
            Set("tokenRows", 8);
            Set("forwardPulseHeat", 1f);
            Set("heatDecayRate", 1.4f);
            Set("candidateBaseHeat", 0.25f);
            Set("paletteEntropyScale", 0.25f);
            Set("entropySmoothing", 0.3f);
            Set("foldDuration", 1f);
            Set("columnRadius", 0.72f);
            Set("haloRadius", 1.08f);
            Set("haloOffset", 0.3f);
            Set("rotationSpeed", 7f);
            Set("glowIntensity", 1.15f);

            MethodInfo validate = typeof(CortexVisualizationSettings).GetMethod("Validate", fields);
            Assert.That(validate, Is.Not.Null);
            Assert.DoesNotThrow(() => validate.Invoke(settings, null));

            Set("haloRadius", 0.5f);
            TargetInvocationException exception = Assert.Throws<TargetInvocationException>(
                () => validate.Invoke(settings, null)
            );
            Assert.That(exception.InnerException, Is.TypeOf<InvalidDataException>());
        }

        [Test]
        public void TinyModelGreedyGenerationIsDeterministic()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            ChatServiceOptions options = TinyUncachedOptions(modelPath);
            using ChatService service = new(options);
            ChatRuntimeInfo info = service.Start();
            Assert.That(info.ContextLength, Is.EqualTo(128));
            Assert.That(info.TransformerBlockCount, Is.EqualTo(4));

            // The tiny model has random weights and a 512-token vocabulary, so drive the raw
            // loop with small ids and disabled stop tokens to validate the decode mechanics.
            int[] prompt = { 2, 105, 10, 25, 50, 106 };
            ChatGenerationOptions generation = new() { MaxNewTokens = 8, Temperature = 0f };
            List<int> first = service.GenerateTokens(prompt, generation, Array.Empty<int>());
            List<int> second = service.GenerateTokens(prompt, generation, Array.Empty<int>());

            Assert.That(first.Count, Is.EqualTo(8));
            Assert.That(second, Is.EqualTo(first));
            Assert.That(first.All(id => id >= 0 && id < 512), Is.True);
        }

        // Trimming is shared by BeginChat and InspectContext, but only InspectContext can be
        // exercised here: the tiny model's 512-token vocabulary cannot accept a real prompt.
        [Test]
        public void ContextTrimsCompleteOldTurnsButKeepsNewestTurn()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            ChatServiceOptions options = TinyUncachedOptions(modelPath);
            using ChatService service = new(options);
            service.Start();
            ChatGenerationOptions generation = new() { MaxNewTokens = 8, Temperature = 0f };
            ChatMessage system = ChatMessage.System("Be concise.");
            ChatMessage newest = ChatMessage.User("Newest question.");
            ChatMessage[] history =
            {
                system,
                ChatMessage.User(string.Join(" ", Enumerable.Repeat("old", 200))),
                ChatMessage.Assistant("Old answer."),
                newest,
            };
            int expectedPromptTokens = service
                .Tokenizer.EncodeWithSpecialTokens(
                    ChatTemplate.BuildPromptText(new[] { system, newest })
                )
                .Count;

            ChatContextSnapshot trimmed = service.InspectContext(history, generation);
            Assert.That(trimmed.PromptTokens, Is.EqualTo(expectedPromptTokens));
            Assert.That(trimmed.Messages, Is.EqualTo(new[] { system, newest }));

            // Digits tokenize one-per-digit under the byte-level split regex, so this
            // message can never be BPE-compressed below the 128-token window.
            ChatMessage oversizedNewest = ChatMessage.User(
                string.Join(" ", Enumerable.Range(0, 300))
            );
            Assert.Throws<ArgumentException>(
                () => service.InspectContext(new[] { system, oversizedNewest }, generation)
            );
        }

        [Test]
        public void ContextInspectionKeepsFittingHistoryAndShrinksReplyBudget()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            ChatServiceOptions options = TinyUncachedOptions(modelPath);
            using ChatService service = new(options);
            service.Start();
            ChatGenerationOptions generation = new() { MaxNewTokens = 48, Temperature = 0f };
            List<ChatMessage> history =
                new()
                {
                    ChatMessage.System("You are concise."),
                    ChatMessage.User("Call me Jumbo."),
                    ChatMessage.Assistant("Sure."),
                    ChatMessage.User("Who am I now?"),
                };

            int fullPromptTokens = 0;
            for (int repeat = 4; repeat < 80; repeat++)
            {
                history[2] = ChatMessage.Assistant(
                    string.Join(" ", Enumerable.Repeat("friendly detail", repeat))
                );
                fullPromptTokens = service
                    .Tokenizer.EncodeWithSpecialTokens(ChatTemplate.BuildPromptText(history))
                    .Count;
                if (fullPromptTokens >= 88 && fullPromptTokens < 120)
                    break;
            }
            Assert.That(fullPromptTokens, Is.InRange(88, 119));

            ChatContextSnapshot context = service.InspectContext(history, generation);
            Assert.That(context.WasTrimmed, Is.False);
            Assert.That(context.Messages.Count, Is.EqualTo(history.Count));
            Assert.That(context.PromptTokens, Is.EqualTo(fullPromptTokens));
            Assert.That(context.AvailableReplyTokens, Is.LessThan(generation.MaxNewTokens));

            // The prompt fits the window but its ChatML ids run past the tiny model's 512-token
            // vocabulary. Sentis would gather out of bounds and take the process down, so the
            // mismatch has to surface as an exception before anything is scheduled.
            ArgumentException mismatch = Assert.Throws<ArgumentException>(
                () => service.BeginChat(history, generation)
            );
            Assert.That(mismatch.Message, Does.Contain("512-token"));
        }

        [Test]
        public void TinyModelStreamMatchesBlockingGreedyPathAndEmitsTelemetry()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            ChatServiceOptions options = TinyUncachedOptions(modelPath);
            using ChatService service = new(options);
            int[] prompt = { 2, 105, 10, 25, 50, 106 };
            ChatGenerationOptions generation = new() { MaxNewTokens = 8, Temperature = 0f };
            List<int> blocking = service.GenerateTokens(prompt, generation, Array.Empty<int>());

            using ChatStream stream = service.BeginStream(prompt, generation, Array.Empty<int>());
            List<int> streamed = new();
            int layersSinceToken = 0;
            int layerEvents = 0;
            int tokenEvents = 0;
            stream.LayerExecuted += (_, _, _) =>
            {
                layersSinceToken++;
                layerEvents++;
            };
            stream.TokenSampled += metrics =>
            {
                Assert.That(layersSinceToken, Is.GreaterThan(0));
                Assert.That(metrics.TopCandidates.Count, Is.GreaterThan(0));
                Assert.That(metrics.WindowCapacity, Is.EqualTo(128));
                streamed.Add(metrics.TokenId);
                layersSinceToken = 0;
                tokenEvents++;
            };

            while (stream.Tick(1000)) { }

            Assert.That(stream.State, Is.EqualTo(ChatStreamState.Completed));
            Assert.That(streamed, Is.EqualTo(blocking));
            Assert.That(tokenEvents, Is.EqualTo(blocking.Count));
            Assert.That(layerEvents, Is.GreaterThanOrEqualTo(tokenEvents));
            Assert.That(stream.Result.FinishReason, Is.EqualTo(ChatFinishReason.TokenLimit));
            Assert.That(stream.Result.IsComplete, Is.False);
        }

        [Test]
        public void TinyModelStreamReportsModelStopAndContextLimitSeparately()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            ChatGenerationOptions generation = new() { MaxNewTokens = 8, Temperature = 0f };
            using ChatService service = new(TinyUncachedOptions(modelPath));
            int[] shortPrompt = { 2, 105, 10, 25, 50, 106 };
            int firstToken = service
                .GenerateTokens(shortPrompt, generation, Array.Empty<int>())
                .First();

            using (ChatStream stopped = service.BeginStream(
                shortPrompt,
                generation,
                new[] { firstToken }
            ))
            {
                while (stopped.Tick(1000)) { }
                Assert.That(stopped.Result.FinishReason, Is.EqualTo(ChatFinishReason.StopToken));
                Assert.That(stopped.Result.IsComplete, Is.True);
                Assert.That(stopped.GeneratedIds, Is.Empty);
            }

            int[] nearlyFullPrompt = Enumerable.Repeat(2, 126).ToArray();
            using ChatStream contextLimited = service.BeginStream(
                nearlyFullPrompt,
                generation,
                Array.Empty<int>()
            );
            while (contextLimited.Tick(1000)) { }

            Assert.That(contextLimited.GeneratedIds.Count, Is.EqualTo(2));
            Assert.That(
                contextLimited.Result.FinishReason,
                Is.EqualTo(ChatFinishReason.ContextLimit)
            );
            Assert.That(contextLimited.Result.IsComplete, Is.False);
        }

        [Test]
        public void CancelledStreamReportsCancellation()
        {
            string modelPath = SentisModelPath("Llm_Tiny_Text_128.sentis");
            if (!File.Exists(modelPath))
                Assert.Ignore("Tiny .sentis model not converted yet: " + modelPath);

            using ChatService service = new(TinyUncachedOptions(modelPath));
            using ChatStream stream = service.BeginStream(
                new[] { 2, 105, 10, 25, 50, 106 },
                new ChatGenerationOptions { MaxNewTokens = 8, Temperature = 0f },
                Array.Empty<int>()
            );

            ChatResult result = stream.CancelWithPartialResult();

            Assert.That(result.FinishReason, Is.EqualTo(ChatFinishReason.Cancelled));
            Assert.That(result.IsComplete, Is.False);
        }

        [Test]
        public void TinyKvCacheRetainsPrefixAcrossTurnsAndMatchesRebuild()
        {
            string decodePath = SentisModelPath("Llm_Tiny_Decode_128.sentis");
            if (!File.Exists(decodePath))
                Assert.Ignore("Tiny cached decode model not converted yet: " + decodePath);

            int[] prompt = { 2, 105, 10, 25, 50, 106 };
            ChatGenerationOptions generation = new() { MaxNewTokens = 4, Temperature = 0f };
            List<int> continued;
            int[] extended;
            using (ChatService retained = new(CachedTinyOptions(decodePath)))
            {
                List<int> first = retained.GenerateTokens(prompt, generation, Array.Empty<int>());
                extended = prompt.Concat(first).Concat(new[] { 7, 8 }).ToArray();
                continued = retained.GenerateTokens(extended, generation, Array.Empty<int>());
            }

            using ChatService rebuilt = new(CachedTinyOptions(decodePath));
            List<int> rebuiltResult = rebuilt.GenerateTokens(
                extended,
                generation,
                Array.Empty<int>()
            );
            Assert.That(continued, Is.EqualTo(rebuiltResult));
        }

        [Test]
        public void TinyKvCacheStreamMatchesBlockingGreedyPath()
        {
            string decodePath = SentisModelPath("Llm_Tiny_Decode_128.sentis");
            if (!File.Exists(decodePath))
                Assert.Ignore("Tiny cached decode model not converted yet: " + decodePath);

            int[] prompt = { 2, 105, 10, 25, 50, 106 };
            ChatGenerationOptions generation = new() { MaxNewTokens = 6, Temperature = 0f };
            List<int> blocking;
            using (ChatService blockingService = new(CachedTinyOptions(decodePath)))
                blocking = blockingService.GenerateTokens(prompt, generation, Array.Empty<int>());

            using ChatService streamingService = new(CachedTinyOptions(decodePath));
            using ChatStream stream = streamingService.BeginStream(
                prompt,
                generation,
                Array.Empty<int>()
            );
            int layers = 0;
            stream.LayerExecuted += (_, _, _) => layers++;
            while (stream.Tick(1000)) { }

            Assert.That(stream.State, Is.EqualTo(ChatStreamState.Completed));
            Assert.That(stream.GeneratedIds, Is.EqualTo(blocking));
            Assert.That(layers, Is.GreaterThan(stream.GeneratedIds.Count));
            Assert.That(streamingService.RuntimeInfo.ModelSource, Does.Contain("Decode"));
        }

        [UnityTest]
        public IEnumerator TinyKvCacheGpuStreamUsesBatchedSchedulingAndMatchesBlockingPath()
        {
            string decodePath = SentisModelPath("Llm_Tiny_Decode_128.sentis");
            if (!File.Exists(decodePath))
                Assert.Ignore("Tiny cached decode model not converted yet: " + decodePath);
            if (!SystemInfo.supportsComputeShaders)
                Assert.Ignore("GPUCompute is unavailable on this system.");

            int[] prompt = { 2, 105, 10, 25, 50, 106 };
            ChatGenerationOptions generation = new() { MaxNewTokens = 6, Temperature = 0f };
            List<int> blocking;
            using (
                ChatService blockingService =
                    new(CachedTinyOptions(decodePath, BackendType.GPUCompute))
            )
                blocking = blockingService.GenerateTokens(prompt, generation, Array.Empty<int>());

            using ChatService streamingService =
                new(CachedTinyOptions(decodePath, BackendType.GPUCompute));
            using ChatStream stream = streamingService.BeginStream(
                prompt,
                generation,
                Array.Empty<int>()
            );
            int layerEvents = 0;
            int forwardEvents = 0;
            stream.LayerExecuted += (_, _, _) => layerEvents++;
            stream.ForwardEvaluated += () => forwardEvents++;
            while (stream.Tick(1000))
                yield return null;

            Assert.That(stream.State, Is.EqualTo(ChatStreamState.Completed));
            Assert.That(stream.GeneratedIds, Is.EqualTo(blocking));
            int forwardCount = prompt.Length + stream.GeneratedIds.Count - 1;
            Assert.That(layerEvents, Is.EqualTo(forwardCount));
            Assert.That(forwardEvents, Is.EqualTo(forwardCount));
        }

        [Test]
        public void CortexChatPrefabHasAuthoredUiWiring()
        {
            const string prefabPath = "Assets/Bundles/Prefabs/UI/Components/CortexChat.prefab";
            GameObject root = PrefabUtility.LoadPrefabContents(prefabPath);
            try
            {
                CortexChatController controller = root.GetComponent<CortexChatController>();
                Assert.That(controller, Is.Not.Null);

                SerializedObject serializedController = new(controller);
                string[] requiredReferences =
                {
                    "panelRoot",
                    "matrixView",
                    "statusLabel",
                    "performanceLabel",
                    "contextButton",
                    "contextProgressImage",
                    "contextButtonLabel",
                    "contextPanel",
                    "contextLabel",
                    "compactButton",
                    "tooltipPanel",
                    "tooltipLabel",
                    "messagesScroll",
                    "messagesContent",
                    "messagesLayout",
                    "messagesViewport",
                    "messagesFoldButton",
                    "messagesOpenButton",
                    "userBubblePrefab",
                    "aiBubblePrefab",
                    "thinkingBubblePrefab",
                    "input",
                    "sendButton",
                };
                foreach (string propertyName in requiredReferences)
                {
                    SerializedProperty property = serializedController.FindProperty(propertyName);
                    Assert.That(property, Is.Not.Null, propertyName);
                    Assert.That(property.objectReferenceValue, Is.Not.Null, propertyName);
                }

                CortexMatrixView matrix = root.GetComponentInChildren<CortexMatrixView>(true);
                Assert.That(matrix, Is.Not.Null);
                Assert.That(matrix.Image, Is.Not.Null);
                SerializedObject serializedMatrix = new(matrix);
                Assert.That(
                    serializedMatrix.FindProperty("volume").objectReferenceValue,
                    Is.Not.Null
                );
                CortexMatrixVolume volume = matrix.GetComponent<CortexMatrixVolume>();
                Assert.That(volume, Is.Not.Null);
                SerializedObject serializedVolume = new(volume);
                Assert.That(
                    serializedVolume.FindProperty("volumeCamera").objectReferenceValue,
                    Is.Not.Null
                );
                Assert.That(
                    serializedVolume.FindProperty("volumeShader").objectReferenceValue,
                    Is.Not.Null
                );
                UnityEngine.UI.RawImage contextRing = root
                    .transform.Find("Panel/Content/StatusBar/ContextButton/Progress")
                    .GetComponent<UnityEngine.UI.RawImage>();
                Assert.That(contextRing.material, Is.Not.Null);
                Assert.That(
                    contextRing.material.shader.name,
                    Is.EqualTo("Ratioscope/UI/CortexLoadingRing")
                );
                Assert.That(contextRing.material.HasProperty("_Progress"), Is.True);
                TMP_InputField input = root.GetComponentInChildren<TMP_InputField>(true);
                Assert.That(input, Is.Not.Null);
                Assert.That(input.lineType, Is.EqualTo(TMP_InputField.LineType.MultiLineNewline));
                Assert.That(root.transform.Find("Panel/ContextPanel"), Is.Not.Null);
                Assert.That(
                    root.transform.Find("Panel/Content/Messages/MessagesFoldButton"),
                    Is.Not.Null
                );
                Assert.That(
                    root.transform.Find("Panel/Content/Messages/MessagesOpenButton"),
                    Is.Not.Null
                );
                UnityEngine.UI.LayoutElement inputLayout = root
                    .transform.Find("Panel/Content/InputRow")
                    .GetComponent<UnityEngine.UI.LayoutElement>();
                Assert.That(inputLayout.flexibleHeight, Is.Zero);
                UnityEngine.UI.VerticalLayoutGroup contentLayout = root
                    .transform.Find("Panel/Content")
                    .GetComponent<UnityEngine.UI.VerticalLayoutGroup>();
                Assert.That(contentLayout.childForceExpandHeight, Is.False);

                MethodInfo setMessagesCollapsed = typeof(CortexChatController).GetMethod(
                    "SetMessagesCollapsed",
                    BindingFlags.Instance | BindingFlags.NonPublic
                );
                Assert.That(setMessagesCollapsed, Is.Not.Null);
                setMessagesCollapsed.Invoke(controller, new object[] { true });

                Transform messages = root.transform.Find("Panel/Content/Messages");
                Assert.That(
                    messages.GetComponent<UnityEngine.UI.LayoutElement>().preferredHeight,
                    Is.EqualTo(56f)
                );
                Assert.That(messages.Find("Viewport").gameObject.activeSelf, Is.True);
                Assert.That(messages.Find("MessagesFoldButton").gameObject.activeSelf, Is.False);
                Assert.That(messages.Find("MessagesOpenButton").gameObject.activeSelf, Is.True);
                Assert.That(
                    root.transform.Find("Panel/Content/MatrixFrame/DimensionToggle"),
                    Is.Null
                );
                Assert.That(root.transform.Find("OpenCortex"), Is.Null);
                Assert.That(root.transform.Find("Panel/Close"), Is.Null);
                Assert.That(root.GetComponentInChildren<UILoading>(true), Is.Null);

                GameObject bubble = AssetDatabase.LoadAssetAtPath<GameObject>(
                    "Assets/Bundles/Prefabs/UI/Components/ChatMessage/MessageBubble.prefab"
                );
                Assert.That(
                    bubble.transform.Find("Speaker").GetComponent<TMP_Text>().text,
                    Is.EqualTo("ai")
                );
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }

            const string infoPath = "Assets/Bundles/Prefabs/UI/Components/UIInfo.prefab";
            GameObject infoRoot = PrefabUtility.LoadPrefabContents(infoPath);
            try
            {
                UIInfo info = infoRoot.GetComponent<UIInfo>();
                Assert.That(info, Is.Not.Null);
                Assert.That(info.ConfigButton, Is.Not.Null);
                Assert.That(info.HelpButton, Is.Not.Null);
                Assert.That(info.FillButton, Is.Not.Null);
                Assert.That(info.ConfigButton.targetGraphic.raycastTarget, Is.True);
                Assert.That(info.HelpButton.targetGraphic.raycastTarget, Is.True);
                Assert.That(info.FillButton.targetGraphic.raycastTarget, Is.True);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(infoRoot);
            }
        }

        [Test]
        public void CortexChatEnterRemovesOnlyTheNewlineInsertedByTmp()
        {
            const System.Reflection.BindingFlags flags =
                System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic;
            System.Reflection.MethodInfo method = typeof(CortexChatController).GetMethod(
                "RemoveInsertedNewline",
                flags
            );

            Assert.That(method, Is.Not.Null);
            Assert.That(method.Invoke(null, new object[] { "hello\n", 6 }), Is.EqualTo("hello"));
            Assert.That(
                method.Invoke(null, new object[] { "hello\nworld", 6 }),
                Is.EqualTo("helloworld")
            );
            Assert.That(method.Invoke(null, new object[] { "hello", 5 }), Is.EqualTo("hello"));
        }

        [Test]
        public void CortexChatCompactionHasNoAutomaticReplyPath()
        {
            const System.Reflection.BindingFlags flags =
                System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.NonPublic;

            Assert.That(typeof(CortexCore).GetMethod("BeginReplyOrCompact", flags), Is.Null);
            Assert.That(
                typeof(CortexChatController).GetMethod("BeginReplyOrCompact", flags),
                Is.Null
            );
            System.Reflection.MethodInfo compact = typeof(CortexCore).GetMethod(
                "BeginCompaction",
                flags
            );
            Assert.That(compact, Is.Not.Null);
            Assert.That(compact.GetParameters(), Is.Empty);
        }

        [Test]
        public void CortexLoadingEventsDriveOuterHudOverlay()
        {
            GameObject sourceObject = new("CortexSource");
            CortexCore source = sourceObject.AddComponent<CortexCore>();
            GameObject overlayPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                "Assets/Bundles/Prefabs/UI/Shared/Overlay.prefab"
            );
            GameObject overlay = Object.Instantiate(overlayPrefab);
            GameObject binderObject = new("CortexLoadingBinder");
            binderObject.SetActive(false);
            CortexHudLoadingBinder binder = binderObject.AddComponent<CortexHudLoadingBinder>();
            try
            {
                UILoading loading = overlay.GetComponent<UILoading>();
                SerializedObject serializedBinder = new(binder);
                serializedBinder.FindProperty("source").objectReferenceValue = source;
                serializedBinder.FindProperty("loadingView").objectReferenceValue = loading;
                serializedBinder.ApplyModifiedPropertiesWithoutUndo();
                binderObject.SetActive(true);

                const System.Reflection.BindingFlags eventFlags =
                    System.Reflection.BindingFlags.Instance
                    | System.Reflection.BindingFlags.NonPublic;
                typeof(CortexHudLoadingBinder)
                    .GetMethod("OnEnable", eventFlags)
                    .Invoke(binder, null);
                Action started = (Action)
                    typeof(CortexCore).GetField("ModelLoadingStarted", eventFlags).GetValue(source);
                Action finished = (Action)
                    typeof(CortexCore)
                        .GetField("ModelLoadingFinished", eventFlags)
                        .GetValue(source);

                started.Invoke();
                Assert.That(loading.IndeterminateVisual.activeInHierarchy, Is.True);
                finished.Invoke();
                Assert.That(loading.IndeterminateVisual.activeSelf, Is.False);
            }
            finally
            {
                Object.DestroyImmediate(binderObject);
                Object.DestroyImmediate(overlay);
                Object.DestroyImmediate(sourceObject);
            }
        }

        [Test]
        public void LoadingOverlayShowsAuthoredIndeterminateVisualForTokenLoading()
        {
            const string prefabPath = "Assets/Bundles/Prefabs/UI/Shared/Overlay.prefab";
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            Assert.That(prefab, Is.Not.Null);

            GameObject instance = Object.Instantiate(prefab);
            try
            {
                UILoading loading = instance.GetComponent<UILoading>();
                Assert.That(loading, Is.Not.Null);
                Assert.That(loading.ProgressFillImage, Is.Null);
                Assert.That(loading.IndeterminateVisual, Is.Not.Null);
                UnityEngine.UI.RawImage ring =
                    loading.IndeterminateVisual.GetComponent<UnityEngine.UI.RawImage>();
                Assert.That(ring, Is.Not.Null);
                Assert.That(ring.material, Is.Not.Null);
                Assert.That(
                    ring.material.shader.name,
                    Is.EqualTo("Ratioscope/UI/CortexLoadingRing")
                );

                int token = loading.BeginLoading();
                Assert.That(loading.IndeterminateVisual.activeSelf, Is.True);
                Assert.That(loading.LoadingOverlay.enabled, Is.False);
                TMPro.TMP_Text label = instance.GetComponentInChildren<TMPro.TMP_Text>(true);
                Assert.That(label, Is.Not.Null);
                Assert.That(
                    label.transform.parent,
                    Is.Not.EqualTo(loading.IndeterminateVisual.transform)
                );

                loading.EndLoading(token);
                Assert.That(loading.IndeterminateVisual.activeSelf, Is.False);
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        [UnityTest]
        [Explicit("Loads the production uint8 decode artifact and runs end-to-end generation.")]
        [Timeout(3600000)]
        public IEnumerator FullModelAnswersPong()
        {
            string modelPath = SentisModelPath("Llm_Text_2048.sentis");
            string decodePath = SentisModelPath("Llm_Decode_2048.sentis");
            if (!File.Exists(modelPath) && !File.Exists(decodePath))
                Assert.Ignore("No full LLM .sentis model has been converted yet.");

            ChatServiceOptions options = SystemSettings.CreateServiceOptions(
                LlmSystemOption.Gpu1_7B_2048
            );
            using ChatService service = new(options);
            using ChatStream stream = service.BeginChat(
                new[]
                {
                    ChatMessage.System("You are concise."),
                    ChatMessage.User("Reply with exactly PONG."),
                },
                new ChatGenerationOptions
                {
                    MaxNewTokens = 8,
                    Temperature = 0f,
                    EnableThinking = false,
                }
            );
            List<double> tokenSeconds = new();
            stream.TokenSampled += metrics =>
            {
                if (!metrics.IsStopToken)
                    tokenSeconds.Add(metrics.ElapsedSeconds);
            };
            while (stream.Tick(1000))
                yield return null;

            ChatResult result = stream.Result;
            Assert.That(tokenSeconds, Is.Not.Empty);
            double tokenRate = tokenSeconds.Count / tokenSeconds.Sum();
            TestContext.Out.WriteLine(
                $"GPU stream: {tokenSeconds.Count} tokens at {tokenRate:0.00} token/s "
                    + $"({tokenSeconds.Average():0.000}s/token mean)."
            );

            Assert.That(result.Content, Does.Contain("PONG"));
            Assert.That(result.GeneratedTokens, Is.GreaterThan(0));
        }

        static List<ChatMessage> FixtureMessages()
        {
            return Fixtures
                .chatMessages.Select(message => new ChatMessage(message.role, message.content))
                .ToList();
        }

        static void AssertStreamingResponse(
            string raw,
            string expectedContent,
            string expectedThinking,
            bool expectedThinkingStarted
        )
        {
            const System.Reflection.BindingFlags flags =
                System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic;
            System.Reflection.MethodInfo method = typeof(ChatService).GetMethod(
                "ParseStreamingResponse",
                flags
            );
            object[] arguments = { raw, null, null, false };

            method.Invoke(null, arguments);

            Assert.That(arguments[1], Is.EqualTo(expectedContent));
            Assert.That(arguments[2], Is.EqualTo(expectedThinking));
            Assert.That(arguments[3], Is.EqualTo(expectedThinkingStarted));
        }

        static ChatServiceOptions CachedTinyOptions(
            string decodePath,
            BackendType backend = BackendType.CPU
        )
        {
            ChatServiceOptions options = SystemSettings.CreateServiceOptions(LlmSystemOption.Tiny);
            options.DecodeModelPath = decodePath;
            options.Backend = backend;
            return options;
        }

        static ChatServiceOptions TinyUncachedOptions(string modelPath)
        {
            ChatServiceOptions options = SystemSettings.CreateServiceOptions(LlmSystemOption.Tiny);
            options.ModelPath = modelPath;
            options.DecodeModelPath = null;
            options.Backend = BackendType.CPU;
            return options;
        }
    }
}
